# Generated by Django 5.1.3 on 2024-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("duplex", "Duplex"),
                            ("penthouse", "Penthouse"),
                            ("building", "Building"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("rent", "Rent")], max_length=10
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("area", models.FloatField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("location", models.JSONField()),
                ("features", models.JSONField(blank=True, null=True)),
                ("images", models.JSONField()),
                ("amenities", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("favorites", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("is_main", models.BooleanField(default=False)),
            ],
        ),
    ]
