# Generated by Django 5.1.3 on 2024-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="propertyimage",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
