# Generated by Django 5.1.3 on 2024-11-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_location_alter_propertyimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.location",
            ),
        ),
    ]
